### PR TITLE
add README

### PR DESCRIPTION
**Pull request by nntai**
Ref #3 
@eprikazc
- Add README

### CODE REVIEW

**Comment by monkeypants** [comment]
Those zigvy references are not appropriate. Since GoSource are paying for this, you should put our advert in there not yours :)

**Comment by nntai** [comment]
I've updated the README. Can you please check it again? Thank you

**Comment by monkeypants** [comment]
looks OK to me, but really we need review from @eprikazc now.

**Comment by eprikazc** [comment]
Yup, this looks good to me too. 
However, I am getting error when running it. First I installed cookiecutter via `pip3 install cookiecutter`. Then:
```
cookiecutter gs-expo-cookiecutter
...
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 876, in subparse
    self.stream.expect('variable_end')
  File "/usr/local/lib/python3.7/site-packages/jinja2/lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got ':'
  File "./components/SettingComponent/SettingComponent.js", line 34
    <Text style={{ fontWeight: 'bold' }}>{section.title}</Text>
```

**Comment by nntai** [comment]
thank you, let me check it

**Comment by nntai** [comment]
@eprikazc  I've fixed the bug and tested the cookiecutter again. Can you check it one more time?

**Comment by eprikazc** [comment]
Yes, the fix helped. I was able to create project from this cookiecutter template and run the app (using Android dev studio emulator).
Overall, this README looks good to me.

**Pull request merged**
